# Generated by Django 6.0.7 on 2026-07-18 21:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        help_text="Unique hardware address. Format: XX:XX:XX:XX:XX:XX",
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid MAC address (e.g., AA:BB:CC:DD:EE:FF)",
                                regex="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                            )
                        ],
                        verbose_name="MAC Address",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="Device hostname if available",
                        max_length=100,
                        null=True,
                        verbose_name="hostname",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Android, iOS, Windows, macOS",
                        max_length=50,
                        null=True,
                        verbose_name="platform",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this device was detected on the network",
                        verbose_name="last seen",
                    ),
                ),
                (
                    "is_trusted",
                    models.BooleanField(
                        default=True,
                        help_text="Trusted devices can bypass some restrictions",
                        verbose_name="trusted device",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device",
                "verbose_name_plural": "devices",
                "ordering": ["-last_seen", "user"],
                "indexes": [
                    models.Index(
                        fields=["mac_address"], name="devices_dev_mac_add_307aef_idx"
                    ),
                    models.Index(
                        fields=["user"], name="devices_dev_user_id_624f27_idx"
                    ),
                ],
            },
        ),
    ]
