# Generated by Django 6.0.7 on 2026-07-19 10:23

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_remove_device_devices_dev_user_id_624f27_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Administratively blocked from network",
                verbose_name="blocked",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="mac_address",
            field=models.CharField(
                db_index=True,
                help_text="Unique hardware address (XX:XX:XX:XX:XX:XX)",
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid MAC address (e.g., AA:BB:CC:DD:EE:FF)",
                        regex="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                    )
                ],
                verbose_name="MAC Address",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["is_blocked"], name="devices_dev_is_bloc_a048fa_idx"
            ),
        ),
    ]
