# Generated by Django 6.0.7 on 2026-07-19 00:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('data_used_mb', models.BigIntegerField(default=0, verbose_name='data used (MB)')),
                ('duration_seconds', models.BigIntegerField(default=0, verbose_name='duration seconds')),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('nas_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='NAS IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='active session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifi_sessions', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WiFi session',
                'verbose_name_plural': 'WiFi sessions',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='portal_sess_user_id_e5e72b_idx'), models.Index(fields=['mac_address'], name='portal_sess_mac_add_78fc4c_idx')],
            },
        ),
    ]
