# Generated by Django 6.0.7 on 2026-07-18 20:22

import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for scalability and security.', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Students/Staff must use @bazeuniversity.edu.ng', max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, help_text='Internal sync with email for Django compatibility.', max_length=150, null=True, unique=True, verbose_name='username')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Recommended: +234xxxxxxxxxx', max_length=128, null=True, region='NG', unique=True, verbose_name='phone number')),
                ('university_id', models.CharField(blank=True, db_index=True, help_text='BU/25A/CSC/001234 format', max_length=50, null=True, verbose_name='university ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('guest', 'Guest')], default='guest', max_length=20, verbose_name='user type')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('one_time_quota_granted', models.BooleanField(default=False, verbose_name='one-time quota granted')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
        ),
    ]
