# Generated by Django 6.0.7 on 2026-07-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_membershipconfig_mode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GuestConfig",
        ),
        migrations.DeleteModel(
            name="MembershipConfig",
        ),
        migrations.DeleteModel(
            name="QuotaConfig",
        ),
        migrations.AddField(
            model_name="customuser",
            name="signup_temp_access_granted",
            field=models.BooleanField(
                default=False, help_text="Signup free window already used or reserved."
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="signup_temp_pending",
            field=models.BooleanField(
                default=False,
                help_text="Entitled; timer starts on first Wi‑Fi allow if policy says so.",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="signup_bonus_granted",
            field=models.BooleanField(
                default=False, help_text="Post-verify one-time bonus already given."
            ),
        ),
    ]
