# Generated by Django 6.0.7 on 2026-07-19 10:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membershipplan_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['duration_days', 'price'], 'verbose_name': 'Membership Plan', 'verbose_name_plural': 'Membership Plans'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'ordering': ['-end_date'], 'verbose_name': 'User Membership', 'verbose_name_plural': 'User Memberships'},
        ),
        migrations.RemoveIndex(
            model_name='usermembership',
            name='memberships_user_id_d4eb32_idx',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='included_quota_gb',
            field=models.PositiveIntegerField(default=0, help_text='Data quota included (GB).'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='max_devices',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum number of registered devices.'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='slug',
            field=models.SlugField(default='default', help_text='Unique identifier for API/frontend use.', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='speed_limit_mbps',
            field=models.PositiveIntegerField(default=0, help_text='0 = Unlimited speed.'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Duration of the plan in days.'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user', 'status'], name='memberships_user_id_1b5292_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['status', 'end_date'], name='memberships_status_3d94c7_idx'),
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='is_active',
        ),
    ]
