# Generated by Django 6.0.7 on 2026-07-18 21:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_type', models.CharField(choices=[('data', 'Data (MB)'), ('time', 'Time (Hours)'), ('session', 'Session Count')], default='data', max_length=20, verbose_name='quota type')),
                ('total_amount', models.BigIntegerField(default=0, verbose_name='total amount')),
                ('used_amount', models.BigIntegerField(default=0, verbose_name='used amount')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotas', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quota',
                'verbose_name_plural': 'quotas',
                'ordering': ['-end_date', 'user'],
            },
        ),
    ]
