# Generated by Django 6.0.7 on 2026-07-19 10:23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotas", "0002_alter_quota_end_date_alter_quota_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quota_type",
                    models.CharField(
                        choices=[
                            ("FREE_DAILY", "Daily Free"),
                            ("MEMBERSHIP", "Membership"),
                            ("GIFT", "Gift"),
                            ("BONUS", "Bonus"),
                            ("MANUAL", "Manual"),
                        ],
                        default="MEMBERSHIP",
                        max_length=30,
                    ),
                ),
                (
                    "total_bytes",
                    models.BigIntegerField(help_text="Total allocated quota in bytes."),
                ),
                (
                    "used_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Bytes already consumed."
                    ),
                ),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quota Allocation",
                "verbose_name_plural": "Quota Allocations",
                "ordering": ["expires_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotaUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bytes_used", models.BigIntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Quota Usage",
                "verbose_name_plural": "Quota Usage Records",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="quota",
            name="quotas_quot_user_id_e0187d_idx",
        ),
        migrations.AddField(
            model_name="quotaallocation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quota_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotausage",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_records",
                to="quotas.quotaallocation",
            ),
        ),
        migrations.RemoveField(
            model_name="quota",
            name="device",
        ),
        migrations.RemoveField(
            model_name="quota",
            name="user",
        ),
        migrations.AddIndex(
            model_name="quotaallocation",
            index=models.Index(
                fields=["user", "is_active"], name="quotas_quot_user_id_9af0b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotaallocation",
            index=models.Index(
                fields=["quota_type"], name="quotas_quot_quota_t_26f7fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotaallocation",
            index=models.Index(
                fields=["expires_at"], name="quotas_quot_expires_50e13d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotaallocation",
            index=models.Index(
                fields=["user", "expires_at"], name="quotas_quot_user_id_8cf9d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotausage",
            index=models.Index(
                fields=["recorded_at"], name="quotas_quot_recorde_a39d15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotausage",
            index=models.Index(
                fields=["allocation"], name="quotas_quot_allocat_f21d22_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Quota",
        ),
    ]
