# Generated by Django 6.0.7 on 2026-07-28 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPolicySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "signup_temp_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="New accounts get one short free window before verify.",
                        verbose_name="Signup free access",
                    ),
                ),
                (
                    "signup_temp_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Length of that one-time window.",
                        verbose_name="Signup minutes",
                    ),
                ),
                (
                    "signup_temp_data_cap_mb",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Max data in signup window. 0 = no cap.",
                        verbose_name="Signup data cap (MB)",
                    ),
                ),
                (
                    "signup_timer_starts_on_first_fas",
                    models.BooleanField(
                        default=True,
                        help_text="On: clock starts at first Wi‑Fi allow. Off: at signup.",
                        verbose_name="Start signup timer on first connect",
                    ),
                ),
                (
                    "verify_student_trial_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="After verify: one free membership for students/staff.",
                        verbose_name="Student trial (days)",
                    ),
                ),
                (
                    "verify_student_trial_plan_slug",
                    models.SlugField(
                        default="premium-trial",
                        help_text="MembershipPlan.slug to use (create plan in Admin if missing).",
                        verbose_name="Student trial plan slug",
                    ),
                ),
                (
                    "verify_non_student_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="After verify: one free time window for non-students.",
                        verbose_name="Non-student free hours",
                    ),
                ),
                (
                    "daily_free_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Verified users with no membership get free minutes each day.",
                        verbose_name="Daily free access",
                    ),
                ),
                (
                    "daily_free_student_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Per day for verified student/staff without a plan.",
                        verbose_name="Daily minutes (student)",
                    ),
                ),
                (
                    "daily_free_non_student_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Per day for verified non-student without a plan.",
                        verbose_name="Daily minutes (non-student)",
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="Africa/Lagos",
                        help_text="Day boundary for daily free and ad limits.",
                        max_length=64,
                        verbose_name="Daily reset timezone",
                    ),
                ),
                (
                    "ad_reward_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Guests and verified non-members can earn time via ads.",
                        verbose_name="Ad rewards",
                    ),
                ),
                (
                    "ad_reward_minutes",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Access time after one completed ad.",
                        verbose_name="Minutes per ad",
                    ),
                ),
                (
                    "ad_reward_data_cap_mb",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Optional data limit on an ad grant. 0 = time only.",
                        verbose_name="Ad data cap (MB)",
                    ),
                ),
                (
                    "ad_daily_limit",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Max ad rewards per user per calendar day.",
                        verbose_name="Ads per day",
                    ),
                ),
                (
                    "ad_grant_expiry_hours",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Unused ad time expires after this many hours.",
                        verbose_name="Ad grant valid for (hours)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Access policy settings",
                "verbose_name_plural": "Access policy settings",
            },
        ),
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "grant_type",
                    models.CharField(
                        choices=[
                            ("SIGNUP_TEMP", "Signup"),
                            ("VERIFY_BONUS", "Verify bonus"),
                            ("DAILY_FREE", "Daily free"),
                            ("AD_REWARD", "Ad reward"),
                            ("MANUAL", "Manual"),
                        ],
                        db_index=True,
                        help_text="Why this window was given.",
                        max_length=32,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Window opens."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, help_text="Hard end (wall clock)."),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(help_text="Max online seconds inside the window."),
                ),
                (
                    "seconds_used",
                    models.PositiveIntegerField(default=0, help_text="Seconds consumed."),
                ),
                (
                    "data_cap_bytes",
                    models.BigIntegerField(default=0, help_text="Max bytes in window. 0 = no cap."),
                ),
                ("bytes_used", models.BigIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, help_text="Off = ignored."),
                ),
                (
                    "grant_day",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Local day for daily/ad caps.",
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Account that may use this window.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Access grant",
                "verbose_name_plural": "Access grants",
                "ordering": ["-expires_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "expires_at"],
                        name="access_poli_user_id_2e2585_idx",
                    ),
                    models.Index(
                        fields=["user", "grant_type", "grant_day"],
                        name="access_poli_user_id_eb81fc_idx",
                    ),
                ],
            },
        ),
    ]
