# Generated by Django 6.0.7 on 2026-09-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_policy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspolicysettings",
            name="student_email_domains",
            field=models.CharField(
                default="bazeuniversity.edu.ng,bazeuniversity.ng",
                help_text="Comma-separated domains allowed for student trial (e.g. bazeuniversity.edu.ng).",
                max_length=255,
            ),
        ),
    ]
