# Generated by Django 6.0.7 on 2026-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_policy", "0002_accesspolicysettings_student_email_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspolicysettings",
            name="student_email_domains",
            field=models.CharField(
                default="bazeuniversity.edu.ng,bazeuniversity.ng",
                help_text="Comma-separated domains for campus trial (student/staff).",
                max_length=255,
            ),
        ),
    ]
